#!/usr/bin/python
import re

def get_links():
	with open('../data/links') as datahand:

		links = []
		data = datahand.read()[:-1].split('\n\n')

		for data_point in data:
			currentlinks = []
			for i in data_point.split('\n'):
				title = re.split('\t+', i)[0]
				link = re.split('\t+', i)[1]
				currentlinks.append([title, link])
			links.append(currentlinks)
		return links
get_links()


def generate_links_html(links_input):
	op = ""
	for i in range(len(links_input)):
		colorcode = (i + 1) % 4
		colorcode += 1
		op += f"<div class=\"links {colorcode}\">\n"
		op += f"<a href=\"{links_input[i][0][1]}\" class=\"linkstitle\">{links_input[i][0][0]}</a>\n"
		links_input[i] = links_input[i][1:]
		for j in links_input[i]:
			op += f"<a href=\"{j[1]}\" class=\"link\">{j[0]}</a>\n"
		op += "</div>\n"
	# Remove the last \n
	op = op[:-1]
	return op


with open('../data/template_start') as starthand, open('../data/template_end') as endhand:
	print(starthand.read())
	print(generate_links_html(get_links()))
	print(endhand.read())